export { default as SearchBar } from './SearchBar'
export { default as Navbar } from './Navbar'
export { default as MovieCard } from './MovieCard'
// export { default as MovieList } from './MovieList'
export { default as MovieDetails } from './MovieDetails'