export { default as Navbar } from './Navbar'
export { default as MovieCard } from './MovieCard'
export { default as Header } from './Header'
export { default as Details } from './Details'
export { default as Genres } from './Genres'
export { default as CustomPaging } from './CustomPaging'
export { default as Carousel } from './Carousel'